### ISSUE TITLE
Outdated pod-identity-webhook version includes a bug that disallows injection of AWS_STS_REGIONAL_ENDPOINTS=regional 

### ISSUE THREAD

**Issue by matveidner** [openshift/aws-pod-identity-webhook#165]
VPCE requires [SetRegion and SetEndpoint](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_sts_vpce.html#:~:text=After%20you%20create%20the%20VPC%20endpoint%2C%20you%20must%20use%20the%20matching%20regional%20endpoint%20to%20send%20your%20AWS%20STS%20requests.%20AWS%20STS%20recommends%20that%20you%20use%20both%20the%20setRegion%20and%20setEndpoint%20methods%20to%20make%20calls%20to%20a%20Regional%20endpoint.) parameters explicitly defined to be automatically used over the global (default) STS endpoint. The AWS-Pod-Identity-Webhook operator on is still the initial [version (v0.1.0)](https://github.com/openshift/aws-pod-identity-webhook/tree/v0.1.0) which currently cannot set these parameters, because of https://github.com/aws/amazon-eks-pod-identity-webhook/pull/120. Regionality should be either set true by default or the operator should be updated to a version that allows env injection w/ sa annotation.

Given this bug that was solved later in EKS, when is this component intended to be updated? The deployed version in our  4.13 cluster is the v0.1.0, but this repository has branches for releases that seemingly covered this issue.
Our requirement is to be able to restrict cross-account IRSA conditionally and utilize an interface endpoint for regional sts.

**Comment by abutcher** [comment]
https://github.com/openshift/aws-pod-identity-webhook/pull/166 will land upstream rebase in the 4.15 branch when it opens. We'll look into backporting once merged.

**Comment by bq0x1** [comment]
@abutcher that's great. We appreciate also your attention to this issue and look forward to its swift resolution. Thx for your assistance.

**Comment by bq0x1** [comment]
@abutcher is it also possible to backport it to 4.14?
